package glr

// Command is a glr command, for completion and symbol info when
// golars-lsp isn't available.
type Command struct {
	Name, Signature, Summary string
	// ArgKind hints what the first argument is: "path", "column",
	// "frame", "count" or empty.
	ArgKind string
}

// Commands lists the glr commands. It mirrors script.Commands in golars
// (script/spec.go) at the time of writing; golars-lsp, when installed,
// knows the commands of the golars version in use.
var Commands = []Command{
	{"load", "load <path> [as NAME]", "Load a csv/parquet/arrow/ipc file as the focused frame (or staged under NAME).", "path"},
	{"use", "use <NAME>", "Switch focus to a clone of a named frame.", "frame"},
	{"stash", "stash <NAME>", "Snapshot the current focus as NAME for later `.use`.", ""},
	{"frames", "frames", "List loaded frames.", ""},
	{"drop_frame", "drop_frame <NAME>", "Release a named frame.", "frame"},
	{"save", "save <path>", "Collect focused pipeline and write to disk.", "path"},
	{"show", "show", "Alias for head 10; prints first rows.", ""},
	{"ishow", "ishow", "Open the focused pipeline in the interactive browse TUI.", ""},
	{"browse", "browse", "Alias for `ishow`.", ""},
	{"schema", "schema", "Print column names and dtypes.", ""},
	{"describe", "describe", "Per-column summary stats (count/null/mean/std/quartiles).", ""},
	{"head", "head [N]", "Collect and print first N rows (default 10).", "count"},
	{"tail", "tail [N]", "Collect and print last N rows (default 10).", "count"},
	{"select", "select <col>[,<col>...]", "Project columns (lazy).", "column"},
	{"drop", "drop <col>[,<col>...]", "Drop columns (lazy).", "column"},
	{"filter", "filter <col> <op> <value> [and|or ...]", "Filter rows by a predicate (lazy).", "column"},
	{"sort", "sort <col> [asc|desc]", "Sort by one column (lazy).", "column"},
	{"limit", "limit <N>", "Keep the first N rows (lazy).", "count"},
	{"groupby", "groupby <k1,k2,...> <col:op[:alias]>...", "Group by KEYS, aggregate via col:op[:alias].", "column"},
	{"join", "join <path|NAME> on <key> [inner|left|cross]", "Join focus with a file or named frame on KEY.", "frame"},
	{"explain", "explain", "Print logical plan, optimiser trace, optimised plan.", ""},
	{"explain_tree", "explain_tree", "Explain rendered as a box-drawn tree.", ""},
	{"tree", "tree", "Alias of explain_tree.", ""},
	{"graph", "graph", "Styled plan tree with lipgloss colour coding (alias: show_graph).", ""},
	{"show_graph", "show_graph", "Alias of graph.", ""},
	{"mermaid", "mermaid", "Emit the plan as a Mermaid flowchart.", ""},
	{"collect", "collect", "Materialise lazy pipeline back into focused source.", ""},
	{"reset", "reset", "Discard the lazy pipeline; keep the source.", ""},
	{"source", "source <path>", "Run another .glr script inline.", "path"},
	{"timing", "timing", "Toggle per-statement timing output.", ""},
	{"info", "info", "Runtime info: Go version, heap, uptime.", ""},
	{"clear", "clear", "Clear the screen.", ""},
	{"help", "help", "Print the command reference.", ""},
	{"exit", "exit", "Quit the REPL.", ""},
	{"quit", "quit", "Quit the REPL.", ""},
	{"reverse", "reverse", "Reverse row order of the current focus.", ""},
	{"sample", "sample <N> [seed]", "Sample N rows (no replacement).", "count"},
	{"shuffle", "shuffle [seed]", "Randomly reorder every row.", ""},
	{"unique", "unique", "Drop duplicate rows over all columns (group-by-every).", ""},
	{"null_count", "null_count", "Per-column null count as a single-row frame.", ""},
	{"glimpse", "glimpse [N]", "Compact peek at the first N rows (default 5).", "count"},
	{"size", "size", "Estimated Arrow byte size of the current pipeline output.", ""},
	{"cast", "cast <col> <dtype>", "Cast a column to the given dtype (i64, i32, f64, f32, bool, str).", "column"},
	{"fill_null", "fill_null <value>", "Replace nulls across all compatible columns.", ""},
	{"drop_null", "drop_null [col...]", "Drop rows with nulls in any (or the listed) columns.", "column"},
	{"rename", "rename <old> as <new>", "Rename a single column.", "column"},
	{"sum", "sum <col>", "Print the sum of the given column.", "column"},
	{"mean", "mean <col>", "Print the mean of the given column.", "column"},
	{"min", "min <col>", "Print the min of the given column.", "column"},
	{"max", "max <col>", "Print the max of the given column.", "column"},
	{"median", "median <col>", "Print the median of the given column.", "column"},
	{"std", "std <col>", "Print the sample standard deviation of the given column.", "column"},
	{"write", "write <path>", "Alias for `save`: materialise the pipeline and write to disk.", "path"},
	{"with_row_index", "with_row_index <name> [offset]", "Prepend an int64 row-index column.", ""},
	{"pwd", "pwd", "Print the REPL working directory.", ""},
	{"ls", "ls [path]", "List files in the given directory (default: cwd).", "path"},
	{"cd", "cd [path]", "Change the REPL working directory (default: home).", "path"},
	{"sum_horizontal", "sum_horizontal <out> [col...]", "Append a row-wise sum column named <out> across selected (or all numeric) columns.", "column"},
	{"mean_horizontal", "mean_horizontal <out> [col...]", "Append a row-wise mean column (nulls skipped).", "column"},
	{"min_horizontal", "min_horizontal <out> [col...]", "Append a row-wise min column.", "column"},
	{"max_horizontal", "max_horizontal <out> [col...]", "Append a row-wise max column.", "column"},
	{"all_horizontal", "all_horizontal <out> [col...]", "Append a row-wise boolean AND column across selected (or all boolean) columns.", "column"},
	{"any_horizontal", "any_horizontal <out> [col...]", "Append a row-wise boolean OR column.", "column"},
	{"sum_all", "sum_all", "One-row frame with the sum of every numeric column.", ""},
	{"mean_all", "mean_all", "One-row frame with the mean of every numeric column.", ""},
	{"min_all", "min_all", "One-row frame with the min of every numeric column.", ""},
	{"max_all", "max_all", "One-row frame with the max of every numeric column.", ""},
	{"std_all", "std_all", "One-row frame with the sample std of every numeric column.", ""},
	{"var_all", "var_all", "One-row frame with the sample variance of every numeric column.", ""},
	{"median_all", "median_all", "One-row frame with the median of every numeric column.", ""},
	{"count_all", "count_all", "One-row frame with the non-null count of every column.", ""},
	{"null_count_all", "null_count_all", "One-row frame with the null count of every column.", ""},
	{"with", "with <name> = <expression>", "Append a derived column via the expression DSL.", ""},
	{"unnest", "unnest <col>", "Project the fields of a struct-typed column as top-level columns.", "column"},
	{"explode", "explode <col>", "Fan out each element of a list-typed column into its own row.", "column"},
	{"upsample", "upsample <col> <every>", "Interpolate a timestamp column at a regular interval.", "column"},
	{"scan_csv", "scan_csv <path> [as NAME]", "Register a lazy scan of a CSV file (push-down friendly).", "path"},
	{"scan_parquet", "scan_parquet <path> [as NAME]", "Register a lazy scan of a Parquet file.", "path"},
	{"scan_ipc", "scan_ipc <path> [as NAME]", "Register a lazy scan of an Arrow IPC file.", "path"},
	{"scan_ndjson", "scan_ndjson <path> [as NAME]", "Register a lazy scan of an NDJSON file.", "path"},
	{"scan_json", "scan_json <path> [as NAME]", "Register a lazy scan of a JSON (array) file.", "path"},
	{"scan_auto", "scan_auto <path> [as NAME]", "Register a lazy scan inferring the reader from the file extension.", "path"},
	{"fill_nan", "fill_nan <value>", "Replace NaN with VALUE in every float column (frame-level).", ""},
	{"forward_fill", "forward_fill [limit]", "Forward-fill nulls (at most LIMIT consecutive, 0 = unlimited).", ""},
	{"backward_fill", "backward_fill [limit]", "Backward-fill nulls. Trailing nulls stay null.", ""},
	{"top_k", "top_k <K> <col>", "Collect the K rows with the largest values in COL (descending).", "count"},
	{"bottom_k", "bottom_k <K> <col>", "Collect the K rows with the smallest values in COL.", "count"},
	{"transpose", "transpose [header_col] [prefix]", "Transpose the focus (numeric/bool columns only).", ""},
	{"unpivot", "unpivot <id_cols> [val_cols]", "Reshape wide to long (melt). ID_COLS/VAL_COLS are comma-separated lists.", "column"},
	{"partition_by", "partition_by <keys>", "Split the focus into one frame per distinct key combination; prints a summary.", "column"},
	{"skew", "skew <col>", "Print the skewness of COL (polars-default, biased).", "column"},
	{"kurtosis", "kurtosis <col>", "Print the excess kurtosis of COL.", "column"},
	{"approx_n_unique", "approx_n_unique <col>", "HyperLogLog estimate of the number of distinct values in COL.", "column"},
	{"corr", "corr <col1> <col2>", "Print the Pearson correlation between two numeric columns.", "column"},
	{"cov", "cov <col1> <col2>", "Print the sample covariance (ddof=1) between two numeric columns.", "column"},
	{"pivot", "pivot <index_cols> <on_col> <values_col> [agg]", "Long-to-wide pivot. agg: first/sum/mean/min/max/count (default first).", "column"},
}
