package glr

// Functions lists the functions glr expressions accept, by namespace:
// "" for methods on any value (x.round(2) or round(x, 2)), "free" for
// top-level functions, and str, dt, list, arr, struct, name, bin and cat
// for namespaced ones (ts.dt.year() or dt.year(ts)). It mirrors
// exprparse.Functions() in golars at the time of writing.
var Functions = map[string][]string{
	"":       {"abs", "add", "alias", "all", "and", "and_expr", "any", "approx_n_unique", "arccos", "arccosh", "arcsin", "arcsinh", "arctan", "arctan2", "arctanh", "arg_max", "arg_min", "arg_sort", "arg_true", "arg_unique", "backward_fill", "between", "bitwise_and", "bitwise_count_ones", "bitwise_count_zeros", "bitwise_leading_ones", "bitwise_leading_zeros", "bitwise_or", "bitwise_trailing_ones", "bitwise_trailing_zeros", "bitwise_xor", "bottom_k", "bottom_k_by", "cast", "cbrt", "ceil", "clip", "cos", "cosh", "cot", "count", "cum_count", "cum_max", "cum_min", "cum_prod", "cum_sum", "cumulative_eval", "cut", "degrees", "diff", "div", "dot", "drop_nans", "drop_nulls", "entropy", "entropy_with", "eq", "eq_missing", "ewm_mean", "ewm_std", "ewm_var", "exclude", "exp", "explode", "expm1", "extend_constant", "fill_nan", "fill_null", "fill_null_expr", "filter", "first", "flatten", "floor", "floor_div", "forward_fill", "gather", "gather_every", "gather_idx", "ge", "get", "gt", "has_nulls", "hash", "hash_values", "head", "hist", "implode", "index_of", "interpolate", "interpolate_by", "is_between", "is_close", "is_duplicated", "is_finite", "is_first_distinct", "is_in", "is_infinite", "is_last_distinct", "is_na_n", "is_not_na_n", "is_not_null", "is_null", "is_unique", "item", "kurtosis", "last", "le", "len", "limit", "log", "log10", "log1p", "log2", "log_base", "lower_bound", "lt", "max", "max_by", "mean", "median", "min", "min_by", "mod", "mode", "mul", "n_unique", "nan_max", "nan_min", "ne", "ne_missing", "neg", "not", "null_count", "or", "or_expr", "over", "pct_change", "peak_max", "peak_min", "pow", "pow_expr", "product", "q_cut", "q_cut_n", "qcut", "quantile", "quantile_with", "radians", "rank", "rank_with", "reinterpret", "repeat_by", "replace", "replace_strict", "reshape", "reverse", "rle", "rle_id", "rolling_kurtosis", "rolling_max", "rolling_max_by", "rolling_mean", "rolling_mean_by", "rolling_median", "rolling_median_by", "rolling_min", "rolling_min_by", "rolling_quantile", "rolling_quantile_by", "rolling_rank", "rolling_skew", "rolling_std", "rolling_std_by", "rolling_sum", "rolling_sum_by", "rolling_var", "rolling_var_by", "round", "round_sig_figs", "sample", "sample_frac", "search_sorted", "shift", "shuffle", "sign", "sin", "sinh", "skew", "slice", "sort", "sort_by", "sort_with", "sqrt", "std", "std_ddof", "sub", "sum", "tail", "tan", "tanh", "to_physical", "top_k", "top_k_by", "true_div", "unique", "unique_counts", "upper_bound", "value_counts", "var", "var_ddof", "xor"},
	"arr":    {"all", "any", "arg_max", "arg_min", "contains", "count_matches", "explode", "first", "get", "head", "join", "last", "len", "max", "mean", "median", "min", "n_unique", "reverse", "shift", "slice", "sort", "std", "sum", "tail", "to_list", "to_struct", "unique", "var"},
	"bin":    {"contains", "decode", "encode", "ends_with", "get", "head", "reinterpret", "size", "slice", "starts_with", "tail"},
	"cat":    {"ends_with", "get_categories", "len_bytes", "len_chars", "slice", "starts_with"},
	"dt":     {"add_business_days", "cast_time_unit", "century", "combine", "convert_time_zone", "date", "datetime", "day", "days_in_month", "epoch", "hour", "is_business_day", "is_leap_year", "iso_year", "microsecond", "millennium", "millisecond", "minute", "month", "month_end", "month_start", "nanosecond", "offset_by", "offset_by_expr", "ordinal_day", "quarter", "replace", "replace_time_zone", "replace_time_zone_with", "round", "second", "strftime", "time", "timestamp", "to_string", "total_days", "total_fractional", "total_hours", "total_microseconds", "total_milliseconds", "total_minutes", "total_nanoseconds", "total_seconds", "total_seconds_fractional", "truncate", "week", "weekday", "with_time_unit", "year"},
	"free":   {"all", "all_horizontal", "any_horizontal", "arctan2", "arg_where", "coalesce", "col", "concat_list", "concat_str", "corr", "cov", "cum_sum_horizontal", "date", "date_range", "datetime", "datetime_range", "duration", "element", "exclude", "field", "format", "int_range", "len", "lit", "max_horizontal", "mean_horizontal", "min_horizontal", "repeat", "struct", "sum_horizontal", "time_range"},
	"list":   {"all", "any", "arg_max", "arg_min", "concat", "contains", "count_matches", "diff", "drop_nulls", "eval", "explode", "filter", "first", "gather", "gather_every", "get", "get_with_oob", "head", "item", "join", "join_with", "last", "len", "max", "mean", "median", "min", "n_unique", "reverse", "sample", "sample_fraction", "set_difference", "set_intersection", "set_symmetric_difference", "set_union", "shift", "slice", "sort", "std", "sum", "tail", "to_array", "to_struct", "to_struct_max_width", "unique", "var"},
	"name":   {"keep", "prefix", "prefix_fields", "replace", "suffix", "suffix_fields", "to_lowercase", "to_uppercase"},
	"str":    {"contains", "contains_any", "contains_regex", "count_matches", "decode", "encode", "ends_with", "escape_regex", "explode", "extract", "extract_all", "extract_groups", "extract_many", "find", "find_many", "head", "join", "json_decode", "json_path_match", "len", "len_bytes", "len_chars", "like", "lower", "not_like", "pad_end", "pad_start", "replace", "replace_all", "replace_many", "reverse", "slice", "split", "split_exact", "split_exact_n", "split_inclusive", "split_n", "starts_with", "strip", "strip_chars", "strip_chars_end", "strip_chars_start", "strip_end", "strip_prefix", "strip_start", "strip_suffix", "strptime", "strptime_with", "tail", "to_date", "to_date_with", "to_datetime", "to_datetime_with", "to_integer", "to_lower", "to_lowercase", "to_time", "to_time_with", "to_titlecase", "to_upper", "to_uppercase", "trim", "upper", "z_fill"},
	"struct": {"field", "fields", "json_encode", "rename_fields", "unnest", "with_fields"},
}
