package kernel

import (
	"context"
	"errors"
	"fmt"
	"go/types"
	"maps"
	"os"
	"path"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
)

// The Go side of shared frames (see frames.go). A top-level variable
// holding a golars *DataFrame is saved as Arrow IPC in Frames.Dir rather
// than with gob, which is both how later Go cells restore it and how glr
// cells read it. It is only read when the cell mentions it, and only
// written when the cell assigned a new frame: frames are immutable, so
// the pointer tells.

const framesFile = "gopyter_frames.go"

// frameCellID owns the declarations of frames read from glr. A cell
// that declares the same name replaces them, like any declaration.
const frameCellID = "gopyter:frames"

// isFrameType reports whether t is golars' *dataframe.DataFrame (or an
// alias of it, like golars.DataFrame).
func isFrameType(t types.Type) bool {
	p, ok := types.Unalias(t).(*types.Pointer)
	if !ok {
		return false
	}
	n, ok := types.Unalias(p.Elem()).(*types.Named)
	if !ok || n.Obj().Pkg() == nil {
		return false
	}
	return n.Obj().Name() == "DataFrame" && n.Obj().Pkg().Path() == DataFramePkg
}

const framesSrc = `// Code generated by gopyter. DO NOT EDIT.
package main

import (
	gopyter_context "context"
	gopyter_hex "encoding/hex"
	gopyter_errors "errors"
	gopyter_fmt "fmt"
	gopyter_os "os"
	gopyter_filepath "path/filepath"

	gopyter_dataframe "github.com/Gaurav-Gosain/golars/dataframe"
	gopyter_ipc "github.com/Gaurav-Gosain/golars/io/ipc"
)

// Top-level golars frames are kept as Arrow IPC files shared with glr
// cells. Only the frames the cell mentions are read (gopyterFramesUsed),
// and a frame is written back only when the variable holds another frame
// than the one read.

var gopyterFramesSeen = map[string]*gopyter_dataframe.DataFrame{}

func gopyterFramePath(name string) string {
	dir := gopyter_os.Getenv("GOPYTER_FRAMES_DIR")
	if dir == "" {
		return ""
	}
	return gopyter_filepath.Join(dir, gopyter_hex.EncodeToString([]byte(name))+".arrow")
}

func gopyterLoadFrame(name string) *gopyter_dataframe.DataFrame {
	path := gopyterFramePath(name)
	if path == "" || !gopyterFramesUsed[name] {
		return nil
	}
	df, err := gopyter_ipc.ReadFile(gopyter_context.Background(), path)
	if err != nil {
		if !gopyter_errors.Is(err, gopyter_os.ErrNotExist) {
			gopyter_fmt.Fprintf(gopyter_os.Stderr, "gopyter: frame %s not restored: %v\n", name, err)
		}
		return nil
	}
	gopyterFramesSeen[name] = df
	return df
}

func gopyterSaveFrame(name string, df *gopyter_dataframe.DataFrame) {
	path := gopyterFramePath(name)
	if path == "" || !gopyterFramesUsed[name] || df == gopyterFramesSeen[name] {
		return
	}
	if df == nil {
		if err := gopyter_os.Remove(path); err != nil && !gopyter_errors.Is(err, gopyter_os.ErrNotExist) {
			gopyterVarErrs[name] = err.Error()
			return
		}
		gopyterFramesSaved[name] = [2]int{-1, -1}
		return
	}
	if err := gopyter_os.MkdirAll(gopyter_filepath.Dir(path), 0o755); err != nil {
		gopyterVarErrs[name] = err.Error()
		return
	}
	tmp := path + ".tmp"
	if err := gopyter_ipc.WriteFile(gopyter_context.Background(), tmp, df); err != nil {
		gopyterVarErrs[name] = err.Error()
		return
	}
	if err := gopyter_os.Rename(tmp, path); err != nil {
		gopyterVarErrs[name] = err.Error()
		return
	}
	h, w := df.Shape()
	gopyterFramesSaved[name] = [2]int{h, w}
}
`

// writeFrames writes gopyter_frames.go for the frame variables, or
// removes it when there are none (the golars packages it imports may not
// be available then).
func writeFrames(dir string, frames []string, used map[string]bool) error {
	file := filepath.Join(dir, framesFile)
	if len(frames) == 0 {
		if err := os.Remove(file); err != nil && !errors.Is(err, os.ErrNotExist) {
			return err
		}
		return nil
	}
	var b strings.Builder
	b.WriteString(framesSrc)
	b.WriteString("\nvar gopyterFramesUsed = map[string]bool{")
	for i, n := range slices.Sorted(maps.Keys(used)) {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(strconv.Quote(n))
		b.WriteString(": true")
	}
	b.WriteString("}\n")
	return os.WriteFile(file, []byte(b.String()), 0o644)
}

// framesUsed returns the frame variables that src or a declaration
// mentions.
func framesUsed(src string, decls []*Decl) map[string]bool {
	frames := map[string]bool{}
	for _, d := range decls {
		if d.Var != nil && d.Var.Frame {
			frames[d.Names[0]] = true
		}
	}
	used := map[string]bool{}
	mark := func(s string) {
		for _, w := range Words(s) {
			if frames[w] {
				used[w] = true
			}
		}
	}
	mark(src)
	for _, d := range decls {
		if d.Var == nil || !d.Var.Frame {
			mark(d.Src)
		}
	}
	return used
}

// frameDecl declares a frame read from glr as a Go variable.
func frameDecl(name string) *Decl {
	alias := pkgAlias(DataFramePkg)
	return &Decl{
		Names:  []string{name},
		Src:    fmt.Sprintf("var %s *%s.DataFrame = gopyterLoadFrame(%s)", name, alias, strconv.Quote(name)),
		Raw:    "var " + name + " *dataframe.DataFrame",
		CellID: frameCellID,
		Var:    &VarInfo{Type: FrameType, Imports: map[string]string{alias: DataFramePkg}, Frame: true},
	}
}

// pullFrames reads the glr frames that the cell (src, with imports imps)
// or a declaration mentions and Go hasn't seen, declaring new ones as Go
// variables. It returns the names read.
func (k *Kernel) pullFrames(ctx context.Context, src string, imps []*Import, emit func(Event)) []string {
	if k.Frames == nil {
		return nil
	}
	k.mu.Lock()
	words := Words(src)
	byName := map[string]*Decl{}
	for _, d := range k.decls {
		if d.Var == nil || !d.Var.Frame {
			words = append(words, Words(d.Src)...)
		}
		for _, n := range d.Names {
			byName[n] = d
		}
	}
	pkgs := map[string]bool{}
	for _, i := range slices.Concat(k.imports, imps) {
		if i.Name != "" {
			pkgs[i.Name] = true
		} else {
			pkgs[path.Base(i.Path)] = true
		}
	}
	k.mu.Unlock()

	var read []string
	for _, name := range k.Frames.ForGo(words) {
		d := byName[name]
		var clash string
		switch {
		case !GoName(name):
			clash = "it isn't a Go identifier that can be declared"
		case pkgs[name]:
			clash = "a Go import has that name"
		case d != nil && (d.Var == nil || !d.Var.Frame):
			clash = "Go cells already declare " + name
		}
		if clash != "" {
			msg := fmt.Sprintf("glr frame %s is not visible in Go cells: %s. Rename one of them (glr: stash NEWNAME).", name, clash)
			if k.Frames.Once("go:"+name, msg) {
				emit(Event{Kind: Info, Text: msg})
			}
			continue
		}
		if err := os.MkdirAll(k.Frames.Dir, 0o755); err != nil {
			emit(Event{Kind: Info, Text: err.Error()})
			return read
		}
		if err := k.Frames.exportForGo(ctx, name); err != nil {
			if ctx.Err() != nil {
				return read
			}
			emit(Event{Kind: Info, Text: fmt.Sprintf("glr frame %s not read: %v", name, err)})
			continue
		}
		if d == nil {
			k.mu.Lock()
			k.decls = append(k.decls, frameDecl(name))
			k.mu.Unlock()
		}
		read = append(read, name)
	}
	return read
}

// frameStatus records the frames the program saved and emits the status
// line: frames shared with glr and read from it.
func (k *Kernel) frameStatus(saved map[string][2]int, read []string, emit func(Event)) {
	if k.Frames == nil {
		return
	}
	var shared []string
	for _, name := range slices.Sorted(maps.Keys(saved)) {
		rc := saved[name]
		if rc[0] < 0 {
			k.Frames.GoDropped(name)
			continue
		}
		k.Frames.GoWrote(name, rc[0], rc[1])
		shared = append(shared, name)
	}
	// A frame variable redeclared with another type, or removed.
	k.mu.Lock()
	frames := map[string]bool{}
	for _, d := range k.decls {
		if d.Var != nil && d.Var.Frame {
			frames[d.Names[0]] = true
		}
	}
	k.mu.Unlock()
	for _, f := range k.Frames.List() {
		if f.InGo && !frames[f.Name] {
			k.Frames.GoDropped(f.Name)
		}
	}
	// A frame the cell itself redeclared as something else wasn't read.
	read = slices.DeleteFunc(slices.Clone(read), func(n string) bool { return !frames[n] })
	if line := k.Frames.Status("glr", shared, read); line != "" {
		emit(Event{Kind: Info, Text: line})
	}
}
